name: reader
description: "Epub reader written in Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.0
  shared_preferences: ^2.3.5
  saf_util: ^0.6.2
  saf_stream: ^0.11.1
  filesize: ^2.0.1
  uri_to_file: ^1.0.0
  file: ^7.0.1

  archive: ^4.0.2
  xml: ^6.0.1
  image: ^4.5.2
  path_provider: ^2.1.5
  quiver: ^3.2.2
  collection: ^1.19.0
  provider: ^6.1.2
  flutter_svg: ^2.0.17
  animated_flip_counter: ^0.3.4
  crypto: ^3.0.6
  go_transitions: ^0.7.1
  html: ^0.15.5
  mime: ^2.0.0
  flutter_inappwebview: ^6.1.5
  async: ^2.12.0
  rxdart: ^0.28.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/cover.png
    - assets/images/logo.svg
    - assets/webview/style.css
    - assets/webview/javascript.js
